### ISSUE TITLE
sqljocky5 doesn't work on windows, what should we do?

### ISSUE THREAD

**Issue by raunakhajela** [dart-db/sqljocky5#19]

**Comment by Hexer10** [comment]
Any errors?

**Comment by raunakhajela** [comment]
![39521915_2064211433667555_7110926023385939968_n](https://user-images.githubusercontent.com/6176598/44340515-b4379980-a4a2-11e8-98c2-eb38e5d4a0d6.jpg)

**Comment by tejainece** [comment]
Can you login to mysql using the command:

```
mysql -u root -p
```

**Comment by raunakhajela** [comment]
Yes and here is the program which I am running https://github.com/raunakhajela/dart-tutorials/blob/master/67-selecting-rows/bin/main.dart

**Comment by tejainece** [comment]
Your password is empty. Set a valid password using `mysql` command. You cannot login with empty password using `mysql` client either.

**Comment by raunakhajela** [comment]
I did and it is not working

**Comment by Hexer10** [comment]
Maybe leave out the password parameter if you aren't using any

**Comment by tejainece** [comment]
@raunakhajela Did you mean you changed the password? Change it to something like `asdf1234` (for testing) or something.

Here is an article on how to change the password: https://dev.mysql.com/doc/refman/8.0/en/resetting-permissions.html

**Comment by raunakhajela** [comment]
@tejainece I removed password field and it is working now. Thanks for all the help :+1:

**Comment by tejainece** [comment]
By the way, great work on the Dart tutorial list!

**Comment by raunakhajela** [comment]
Thank you @tejainece . Feel free to rate and fork :)
