### ISSUE TITLE
Support for utf8mb4 character encoding for full Unicode support

### ISSUE THREAD

**Issue by hoylen** [dart-db/sqljocky5#2]
Provide a mechanism so the `utf8mb4` character encoding can be used.

Currently, _sqljocky5_ uses connections with `character_set_client` and `character_set_connection` set to `utf8` (the incomplete, maximum 3-byte per character, implementation of UTF-8 in MySQL). Therefore, _sqljocky5_ cannot handle Unicode characters which are not in the Basic Multilingual Plane, even though the database uses `utf8mb4` (the complete, maximum 4-byte per character, correct implementation of UTF-8).

For example, text containing 𨭎 or 😂 is mangled. The characters get converted to four question marks when inserting/updating, or to one question mark when selecting.

**Comment by hoylen** [comment]
Note: this has to be an **optional** feature, because older versions of MySQL and MariaDB do not have support for `utf8mb4`.

It was [introduced in 2010](https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434), so older versions of MySQL only have support for the incomplete `utf8` character encoding.

**Comment by kaetemi** [comment]
Reference to switch to utf8mb4 only:

https://github.com/nbspou/sqljocky5/commit/8877daedb269633ef326aa864af6d5681989ed68

**Comment by tejainece** [comment]
@kaetemi Send pull request?

**Comment by kaetemi** [comment]
Should we switch fully to utf8mb4, or have an option for it as @hoylen suggests?

The utf8.encode and decode are utf8mb4, so I'm not sure how technically reliable the sql utf8 behaves with those functions when 4byte characters are in the stream of outgoing data. It didn't fail with the case I tried, but the unsupported characters were obviously corrupted.

**Comment by tejainece** [comment]
Optional with `utf8mb4` as default.

**Comment by hoylen** [comment]
Ok by me... since we have (finally) upgraded everything to MariaDB 10.x, which supports utf8mb4.

**Comment by hoylen** [comment]
I see sqljocky5 **2.2.1** seems to open connections with `utf8mb4` encoding.

If it has been deliberately fixed, then this issue can be closed. If it is happening by coincidence or luck, then this issue should be kept open.

**Comment by tejainece** [comment]
It has been deliberately fixed.
