### ISSUE TITLE
Program exits when connecting to a bad server

### ISSUE THREAD

**Issue by hoylen** [dart-db/sqljocky5#3]
When connected to a "bad server", trying to _prepare_ a query crashes the program. No exception is raised, so the program cannot detect the problem.

A "bad server" is one that does not respond as a properly working MySQL server. For example, if the socket connection closes after returning malformed data or no data at all.

This problem was first noticed when the MySQL server was accessed by SSH port forwarding: the port forwarding was established, but the MySQL server was not running. This is different from if trying to directly connect to a MySQL service that wasn't running (in which case a SocketException is correctly raised). Other situations where the problem would occur is if the client was misconfigured and connected to a non-MySQL port: in which case the client would want to print out an error message rather than crashing/exiting.

**Expected behaviour:** an exception is thrown by _sqljocky5_. (This is what the old _sqljocky_ 0.14.0 package did).

**What actually happens:** the program exits/terminates with an exit status of zero (which is misleading).

**How to reproduce the problem:**

Instead of connecting to a real _mysql_ service, start a service that listens on a port and immediately closes any socket connections it receives. This can be done with the _netcat_ command:

```
while true; do echo -n | nc -l 3306; date; done
```

This test program:

```
import 'dart:async';
import 'dart:io';

import 'package:logging/logging.dart';
import 'package:sqljocky5/sqljocky.dart';

Future main(List<String> arguments) async {
  hierarchicalLoggingEnabled = true;
  Logger.root.level = Level.ALL;
  Logger.root.onRecord.listen((LogRecord r) {
    print("${r.time}: ${r.loggerName}: ${r.message}");
  });

  try {
    final dbPool = new ConnectionPool(
        host: "localhost",
        port: 3306,
        user: "test",
        password: "p@ssw0rd",
        db: "testdb",
        useSSL: false,
        max: 5);

    print("Before prepare");
    final query = await dbPool.prepare("SELECT TIMEDIFF(NOW(),UTC_TIMESTAMP)");
    print("After prepare"); // this line is never reached

    final result = await query.execute(<Object>[]);
    Duration databaseTzOffset;
    await result.forEach((row) {
      databaseTzOffset = row[0] as Duration;
    });
    assert(databaseTzOffset != null);

    final localTzOffset = new DateTime.now().timeZoneOffset;

    if (databaseTzOffset == localTzOffset) {
      print("ok: timezones match");
    } else {
      print("error: timezones mismatch");
    }

    dbPool.closeConnectionsWhenNotInUse();

  } on SocketException catch(e) {
    print("Exception:\n  $e\n");
    exit(1);
  }

  print("Done");
}
```

Produces this output:

```
Before prepare
2018-02-23 17:23:34.613640: Query: Getting prepared query for: SELECT TIMEDIFF(NOW(),UTC_TIMESTAMP)
2018-02-23 17:23:34.618559: ConnectionPool: Getting a connection
2018-02-23 17:23:34.618968: ConnectionPool: Number of in-use connections: 0
2018-02-23 17:23:34.619277: ConnectionPool: Creating new pooled cnx#0
2018-02-23 17:23:34.622794: Connection.Lifecycle: Use connection #0
2018-02-23 17:23:34.627722: Connection: opening connection to localhost:3306/testdb
2018-02-23 17:23:34.628966: Connection: hoylen: connection: after BufferedSocket.connect
2018-02-23 17:23:34.659319: BufferedSocket: READ_CLOSED
2018-02-23 17:23:34.661234: BufferedSocket: CLOSED
2018-02-23 17:23:34.663046: Connection.Lifecycle: Release connection #0
2018-02-23 17:23:34.663186: Connection: done
```

Notice that it does not print out "After prepare", "Exception" or "Done". It simply exits with an exit status of zero.

Note: unit tests are not very useful for testing this. The test will timeout.

I've only managed to trace the problem as far as line 112 of _connection_pool_impl.dart_. The call to `cnx.connect` does return a Future, but the program dies/exits/crashes while trying to `await` for that future. The line that says `cnx.autoRelease = true` is never reached.

```
  _createConnection(Completer c) async {
    var cnx = new Connection(this, _pool.length, _maxPacketSize);
    cnx.use();
    cnx.autoRelease = false;
    _pool.add(cnx);
    try {
      await cnx.connect(
          host: _host,
          port: _port,
          user: _user,
          password: _password,
          db: _db,
          useCompression: _useCompression,
          useSSL: _useSSL);
      cnx.autoRelease = true;
      _log.finest("Logged in on cnx#${cnx.number}");
      c.complete(cnx);
    } catch (e, st) {
      if (!(e is MySqlException)) {
        removeConnection(cnx);
      }
      c.completeError(e, st);
    }
  }
```

**Comment by hoylen** [comment]
This problem no longer occurs with sqljocky v2.2.1.

**Comment by tejainece** [comment]
Thanks for verifying it!
