### ISSUE TITLE
The name 'Row' is defined in the libraries 'package

### ISSUE THREAD

**Issue by YuanTianyang** [dart-db/sqljocky5#35]
Android Studio show me the mistake.   I'm a rookie! So......

The name 'Row' is defined in the libraries 'package:flutter/src/widgets/basic.dart' and 'package:sqljocky5/results/row.dart'.

**Comment by YuanTianyang** [comment]
Now I know the method.
import 'package:flutter/src/widgets/basic.dart' as Basic;
But I think there's a better way.

**Comment by tejainece** [comment]
Yes. Probably in your file, two imported libraries have `Row`. The best way is to define is a prefix for sqljocky library.

`import 'package:sqljocky5/sqljocky5.dart' as mysql;`
